// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC_xf57zj4_Q_5yjanqrrOMDfXZtwim08',
    appId: '1:1012773932361:web:0cd6b105de750a669c9e98',
    messagingSenderId: '1012773932361',
    projectId: 'pillpal-62e01',
    authDomain: 'pillpal-62e01.firebaseapp.com',
    storageBucket: 'pillpal-62e01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Hy5jB17nu18rst0GXg9VtxJRlaGZ05Y',
    appId: '1:1012773932361:android:d5cabd36470e03d09c9e98',
    messagingSenderId: '1012773932361',
    projectId: 'pillpal-62e01',
    storageBucket: 'pillpal-62e01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk0w0M9vp4-OvJmr-GrVE7B6CM92kC1zQ',
    appId: '1:1012773932361:ios:0821d71bbb02e7889c9e98',
    messagingSenderId: '1012773932361',
    projectId: 'pillpal-62e01',
    storageBucket: 'pillpal-62e01.appspot.com',
    iosBundleId: 'com.example.pharmacistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk0w0M9vp4-OvJmr-GrVE7B6CM92kC1zQ',
    appId: '1:1012773932361:ios:f2630d12002c58799c9e98',
    messagingSenderId: '1012773932361',
    projectId: 'pillpal-62e01',
    storageBucket: 'pillpal-62e01.appspot.com',
    iosBundleId: 'com.example.pharmacistApp.RunnerTests',
  );
}
